allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': false
  esbuild: true
  mongodb-memory-server: true
  msgpackr-extract: false
  unrs-resolver: true

overrides:
  multer: ^2.4.0
  undici: ^6.28.1
  proxy-addr: ^2.0.8
  fast-uri: ^3.1.8
  brace-expansion@2: ^2.1.7
  brace-expansion@5: ^5.0.12
  tmp: ^0.2.6
